[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_cross = "CRoSk9Dzo7NhunjizbpA9Z9isrcvJyDn3w1cZFFmHUak"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = ""
wallet = "./keys/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
